src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsSynced__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed_By_Queue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed By Queue</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QueuebleJobTest.cls
/**
 * Created by Aleksei on 17.03.2021.
 */
@IsTest
private class QueuebleJobTest {

    @IsTest static void jobTestWithBillingAddress(){

        Id testAccountId = createTestAccountWithAddress();

        List<Contact> relatedContact = [SELECT Id, IsSynced__c, Processed_By_Queue__c
                                            FROM Contact WHERE AccountId = :testAccountId];

        System.assert(testAccountId != null);
        System.assert(relatedContact != null);
        System.assertEquals(relatedContact[0].IsSynced__c, true);
        System.assertEquals(relatedContact[0].Processed_By_Queue__c, false);

        Test.startTest();
        System.enqueueJob(new QueuebleJob());
        Test.stopTest();

        relatedContact = [SELECT Id, IsSynced__c, Processed_By_Queue__c
                                FROM Contact WHERE AccountId = :testAccountId];

        System.assert(testAccountId != null);
        System.assert(relatedContact != null);
        System.assertEquals(relatedContact[0].IsSynced__c, false);
        System.assertEquals(relatedContact[0].Processed_By_Queue__c, true);
    }

    @IsTest static void jobTestWithoutBillingAddress(){

        Id testAccountId = createTestAccountWithoutAddress();

        List<Contact> relatedContact = [SELECT Id, IsSynced__c, Processed_By_Queue__c
        FROM Contact WHERE AccountId = :testAccountId];

        System.assert(testAccountId != null);
        System.assert(relatedContact != null);
        System.assertEquals(relatedContact[0].IsSynced__c, true);
        System.assertEquals(relatedContact[0].Processed_By_Queue__c, false);

        Test.startTest();
        System.enqueueJob(new QueuebleJob());
        Test.stopTest();

        relatedContact = [SELECT Id, IsSynced__c, Processed_By_Queue__c
        FROM Contact WHERE AccountId = :testAccountId];

        System.assert(testAccountId != null);
        System.assert(relatedContact != null);
        System.assertEquals(relatedContact[0].IsSynced__c, true);
        System.assertEquals(relatedContact[0].Processed_By_Queue__c, false);
    }

    private static Id createTestAccountWithAddress(){

        Contact newContact = new Contact(FirstName = 'TestContact', LastName = 'TestContact');
        Account newAccount = new Account(
                Name = 'TestAccount', BillingCity = 'TestCity', BillingCountry = 'TestCountry');

        insert newAccount;

        newContact.AccountId = newAccount.Id;

        insert newContact;
        return newAccount.Id;
    }

    private static Id createTestAccountWithoutAddress(){

        Contact newContact = new Contact(FirstName = 'TestContact', LastName = 'TestContact');
        Account newAccount = new Account(Name = 'TestAccount');

        insert newAccount;

        newContact.AccountId = newAccount.Id;

        insert newContact;
        return newAccount.Id;
    }
}